# Generated by Django 6.0.2 on 2026-03-06 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=20)),
                ('medical_history', models.TextField(blank=True, default='', help_text='Free text. Guardians describe relevant history.')),
                ('allergies', models.TextField(blank=True, default='', help_text='List known allergies.')),
                ('chronic_conditions', models.TextField(blank=True, default='', help_text='Ongoing conditions the care team should know about.')),
                ('emergency_notes', models.TextField(blank=True, default='', help_text='Critical info for emergencies — blood type, emergency contact, etc.')),
            ],
            options={
                'db_table': 'dependents_dependent',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_guardianships', to=settings.AUTH_USER_MODEL)),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships', to='dependents.dependent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dependents_guardianship',
                'unique_together': {('user', 'dependent')},
            },
        ),
    ]
