# Generated by Django 6.0.2 on 2026-03-13 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0002_remove_visittype_requires_attachments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the nurse submitted this report for review.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='visits.visit')),
            ],
            options={
                'db_table': 'reports_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='', help_text='Instructions for the nurse filling this report.')),
                ('visit_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_template', to='visits.visittype')),
            ],
            options={
                'db_table': 'reports_template',
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Machine-readable key e.g. 'wound_condition'.", max_length=100)),
                ('label', models.CharField(help_text="Human-readable label e.g. 'Wound Condition'.", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('blood_pressure', 'Blood Pressure'), ('choice', 'Choice'), ('boolean', 'Boolean'), ('attachment', 'Attachment')], default='text', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('choices', models.JSONField(blank=True, default=list, help_text="Options for choice fields. e.g. ['healing', 'infected', 'stable']")),
                ('order', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, default='', max_length=300)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='reports.reporttemplate')),
            ],
            options={
                'db_table': 'reports_template_field',
                'ordering': ['order'],
                'unique_together': {('template', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('sections_snapshot', models.JSONField(default=list, help_text='Snapshot of all report sections at time of this action.')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='reports.report')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_version',
                'ordering': ['version_number'],
                'indexes': [models.Index(fields=['created_at'], name='reports_ver_created_64daf4_idx')],
                'unique_together': {('report', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True, default='')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='reports.templatefield')),
            ],
            options={
                'db_table': 'reports_section',
                'indexes': [models.Index(fields=['field'], name='reports_sec_field_i_80415a_idx')],
                'unique_together': {('report', 'field')},
            },
        ),
    ]
