# Generated by Django 6.0.2 on 2026-03-16 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='visit_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_template', to='visits.visittype'),
        ),
        migrations.AddField(
            model_name='reportversion',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportversion',
            name='triggered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='reports.reporttemplate'),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='reports.templatefield'),
        ),
        migrations.AddIndex(
            model_name='reportversion',
            index=models.Index(fields=['created_at'], name='reports_ver_created_64daf4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportversion',
            unique_together={('report', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='templatefield',
            unique_together={('template', 'name')},
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['field'], name='reports_sec_field_i_80415a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportsection',
            unique_together={('report', 'field')},
        ),
    ]
