# Generated by Django 6.0.2 on 2026-03-16 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependents', '0001_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('preferred_at', models.DateTimeField(blank=True, help_text="Guardian's preferred visit time. Set at booking, used by admin as reference.", null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Admin-confirmed visit time.', null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('started', 'Started'), ('completed', 'Completed'), ('report_submitted', 'Report Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=20)),
                ('guardian_response', models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('auto_confirmed', 'Auto Confirmed')], help_text='Set to PENDING when admin schedules. Guardian confirms or cancels. Auto-confirmed if no response by deadline.', max_length=20, null=True)),
                ('guardian_response_at', models.DateTimeField(blank=True, null=True)),
                ('guardian_response_deadline', models.DateTimeField(blank=True, help_text="If guardian hasn't responded by this time, visit is auto-confirmed.", null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('guardian_notes', models.TextField(blank=True, default='', help_text='Instructions or context from the guardian at booking time.')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_visits', to=settings.AUTH_USER_MODEL)),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='dependents.dependent')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='hospitals.hospital')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visits_visit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='made_assignments', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_assignments', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='visits.visit')),
            ],
            options={
                'db_table': 'visits_assignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Estimated visit duration in minutes.')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_types', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'visits_visit_type',
                'ordering': ['name'],
                'unique_together': {('hospital', 'name')},
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='visits.visittype'),
        ),
    ]
