# Generated by Django 6.0.2 on 2026-03-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visittype',
            name='requires_attachments',
        ),
        migrations.RemoveField(
            model_name='visittype',
            name='requires_vitals',
        ),
    ]
